"""empty message

Revision ID: 01937b3cd255
Revises: 2823abf206d2
Create Date: 2021-08-10 12:13:15.674501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01937b3cd255'
down_revision = '2823abf206d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multiple__choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multiple__choice_name'), 'multiple__choice', ['name'], unique=True)
    op.add_column('question', sa.Column('is_multiple_choice', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'is_multiple_choice')
    op.drop_index(op.f('ix_multiple__choice_name'), table_name='multiple__choice')
    op.drop_table('multiple__choice')
    # ### end Alembic commands ###
