"""empty message

Revision ID: 2823abf206d2
Revises: ea9772a8142d
Create Date: 2021-08-09 16:27:54.980379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2823abf206d2'
down_revision = 'ea9772a8142d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('division_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'level', ['level_id'], ['id'])
    op.create_foreign_key(None, 'user', 'division', ['division_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'division_id')
    # ### end Alembic commands ###
