"""empty message

Revision ID: 3956301b8aae
Revises: e74da47bf266
Create Date: 2021-09-02 10:15:33.396123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3956301b8aae'
down_revision = 'e74da47bf266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_schedule_test', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_column('candidate_schedule_test', 'status')
    op.add_column('candidate_test', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_column('candidate_test', 'status')
    op.add_column('pdf_test', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_column('pdf_test', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_test', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('pdf_test', 'is_deleted')
    op.add_column('candidate_test', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('candidate_test', 'is_deleted')
    op.add_column('candidate_schedule_test', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('candidate_schedule_test', 'is_deleted')
    # ### end Alembic commands ###
