"""empty message

Revision ID: 397acabcc620
Revises: 2df4f1465558
Create Date: 2021-08-09 16:20:01.433224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397acabcc620'
down_revision = '2df4f1465558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'question', 'division', ['question_division_id'], ['id'])
    op.create_foreign_key(None, 'question', 'level', ['question_level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    # ### end Alembic commands ###
