"""empty message

Revision ID: 45187e70a237
Revises: c4b9237fc82d
Create Date: 2021-08-16 11:26:40.268492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45187e70a237'
down_revision = 'c4b9237fc82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_schedule_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('date_test', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('pdf_test_id', sa.Integer(), nullable=True),
    sa.Column('time_test', sa.Time(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['pdf_test_id'], ['pdf_test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deleted')
    op.drop_table('candidate_test')
    op.drop_table('candidate_schedule_test')
    # ### end Alembic commands ###
