"""empty message

Revision ID: 50fcdc8aa6a3
Revises: d79c0c588ed9
Create Date: 2021-09-02 13:33:52.800955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50fcdc8aa6a3'
down_revision = 'd79c0c588ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdf_test', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_test', sa.Column('duration', mysql.TIME(), nullable=True))
    # ### end Alembic commands ###
