"""empty message

Revision ID: 6d7e4a24db7d
Revises: e01f96bf7482
Create Date: 2021-08-30 09:30:10.307386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7e4a24db7d'
down_revision = 'e01f96bf7482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_test', sa.Column('file_uploaded', sa.Text(), nullable=True))
    op.add_column('pdf_test', sa.Column('duration', sa.Time(), nullable=True))
    op.add_column('psikotest', sa.Column('duration', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psikotest', 'duration')
    op.drop_column('pdf_test', 'duration')
    op.drop_column('candidate_test', 'file_uploaded')
    # ### end Alembic commands ###
