"""empty message

Revision ID: 7e965dc388a8
Revises: cd41b93feef9
Create Date: 2021-08-12 16:19:38.828917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e965dc388a8'
down_revision = 'cd41b93feef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examination', sa.Column('is_multiple_choice', sa.Boolean(), nullable=True))
    op.add_column('multiple_choice', sa.Column('examination_id', sa.Integer(), nullable=True))
    op.drop_constraint('multiple_choice_ibfk_1', 'multiple_choice', type_='foreignkey')
    op.create_foreign_key(None, 'multiple_choice', 'examination', ['examination_id'], ['id'])
    op.drop_column('multiple_choice', 'question_id')
    op.drop_column('question', 'is_multiple_choice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('is_multiple_choice', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('multiple_choice', sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'multiple_choice', type_='foreignkey')
    op.create_foreign_key('multiple_choice_ibfk_1', 'multiple_choice', 'question', ['question_id'], ['id'])
    op.drop_column('multiple_choice', 'examination_id')
    op.drop_column('examination', 'is_multiple_choice')
    # ### end Alembic commands ###
