"""empty message

Revision ID: b84bab5cc1f6
Revises: 18ac7b065d1d
Create Date: 2021-08-09 10:09:16.708007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84bab5cc1f6'
down_revision = '18ac7b065d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidate', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.drop_column('candidate', 'role_id')
    # ### end Alembic commands ###
