"""empty message

Revision ID: c2e0fee43633
Revises: 7ca0b97177d3
Create Date: 2021-08-10 15:11:38.479383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e0fee43633'
down_revision = '7ca0b97177d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psikotest', sa.Column('filename', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psikotest', 'filename')
    # ### end Alembic commands ###
