"""empty message

Revision ID: c8d8134c620b
Revises: b84bab5cc1f6
Create Date: 2021-08-09 10:31:35.401897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d8134c620b'
down_revision = 'b84bab5cc1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'address')
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###
