"""empty message

Revision ID: cd41b93feef9
Revises: c2e0fee43633
Create Date: 2021-08-10 15:18:24.341854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd41b93feef9'
down_revision = 'c2e0fee43633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psikotest', sa.Column('instruction', sa.Text(), nullable=True))
    op.drop_column('psikotest', 'question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psikotest', sa.Column('question', mysql.TEXT(), nullable=True))
    op.drop_column('psikotest', 'instruction')
    # ### end Alembic commands ###
