"""empty message

Revision ID: ce5ed674ad59
Revises: 01937b3cd255
Create Date: 2021-08-10 15:07:36.590770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce5ed674ad59'
down_revision = '01937b3cd255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psikotest__type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('question', sa.Column('examination_id', sa.Integer(), nullable=True))
    op.drop_constraint('question_ibfk_2', 'question', type_='foreignkey')
    op.drop_constraint('question_ibfk_1', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'examination', ['examination_id'], ['id'])
    op.drop_column('question', 'question_level_id')
    op.drop_column('question', 'question_division_id')
    op.drop_column('question', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('question', sa.Column('question_division_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_level_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_ibfk_1', 'question', 'division', ['question_division_id'], ['id'])
    op.create_foreign_key('question_ibfk_2', 'question', 'level', ['question_level_id'], ['id'])
    op.drop_column('question', 'examination_id')
    op.drop_table('examination')
    op.drop_table('psikotest__type')
    # ### end Alembic commands ###
