"""empty message

Revision ID: d79c0c588ed9
Revises: 61a4b849e911
Create Date: 2021-09-02 11:28:28.506724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd79c0c588ed9'
down_revision = '61a4b849e911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examination', sa.Column('duration', sa.Time(), nullable=True))
    op.drop_column('examination', 'is_multiple_choice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examination', sa.Column('is_multiple_choice', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('examination', 'duration')
    # ### end Alembic commands ###
