"""empty message

Revision ID: e74da47bf266
Revises: 6d7e4a24db7d
Create Date: 2021-09-01 13:13:01.867785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e74da47bf266'
down_revision = '6d7e4a24db7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_email', table_name='candidate')
    op.drop_index('ix_candidate_username', table_name='candidate')
    op.drop_table('candidate')
    op.drop_index('ix_multiple_choice_name', table_name='multiple_choice')
    op.drop_index('name', table_name='role')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_index('name', 'role', ['name'], unique=False)
    op.create_index('ix_multiple_choice_name', 'multiple_choice', ['name'], unique=False)
    op.create_table('candidate',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fullname', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='candidate_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_candidate_username', 'candidate', ['username'], unique=False)
    op.create_index('ix_candidate_email', 'candidate', ['email'], unique=False)
    # ### end Alembic commands ###
